services:
  backend:
    build:
      context: ./tech-int3-server
      dockerfile: Dockerfile
    container_name: avito-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: avito-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
